### ISSUE TITLE
[REFACTOR] 잔디 관련 리팩토링

### ISSUE THREAD

**Issue by yooookm** [su-yeong-ice-pork/backend#127]
## 🛠️ Description
잔디 관련 코드 리팩토링 

## ✅ TODO
- [x] 기간 별로 잔디 조회 로직 수정
     - [x] 테스트하기 용이하도록 날짜 객체를 주입 받도록 설정
- [x] 공통 로직 분리
- [x] 레포지토리 함수 최적화
