### ISSUE TITLE
[Feature] 친구 프로필 페이지 기능

### ISSUE THREAD

**Issue by MinseokGo** [su-yeong-ice-pork/backend#140]
## 🚀 Description
친구 프로필 페이지 기능을 작성한다.

## ✅ TODO
- [x] 상대 멤버 정보를 불러오는 API
- [x] 친구 떠나기 API
- [x] 응원 스티커 보내기 API
- [x] 응원 문구 보내기 API
