### ISSUE TITLE
[Feature] 기록장 페이지 기능

### ISSUE THREAD

**Issue by MinseokGo** [su-yeong-ice-pork/backend#143]
## 🚀 Description 
기록장 페이지 기능을 작성한다.

## ✅ TODO
- [x] 공부(기록) 시작 시 공부 상태를 저장할 API
- [x] 친구 목록을 조회하는 API
- [x] 공부 기록 종료 시 공부 상태를 삭제할 서비스 로직
