### ISSUE TITLE
[Feature] 스터디 정보 관리 기능 구현

### ISSUE THREAD

**Issue by yooookm** [su-yeong-ice-pork/backend#146]
## 🚀 Description 
고정/랜덤 스터디에 대한 정보 관리 기능 구현

## ✅ TODO
- [x] 랜덤 스터디 목록 조회
- [x] 랜덤 스터디 상세 조회
- [x] 고정 스터디 목록 조회
- [x] 고정 스터디 상세 조회
- [x] 고정 스터디 생성
- [ ] 초대 코드로 스터디 입장

## 💻 etc.
멤버 조회는 다른 이슈로 올릴 예정
랜덤 스터디 매칭, 자정 삭제 스케쥴링은 후순위로 미룸
