### ISSUE TITLE
[Feature] 홈 화면 조회 기능

### ISSUE THREAD

**Issue by MinseokGo** [su-yeong-ice-pork/backend#28]
## 🚀 Description 
홈 화면 조회 기능을 구현한다.

## ✅ TODO
- [x] 유저 정보를 조회한다.
- [x] 보유 뱃지 목록을 조회한다.
- [x] 스트릭 및 총 공부시간을 조회한다.
- [x] 월간 잔디밭을 조회한다.
- [ ] 일별 잔디를 조회한다. (기능 삭제)
- [x] 연간 잔디밭을 조회한다.
- [x] 혼자 인증하기 기능을 구현한다.
- [ ] 함께 인증하기 기능을 구현한다.
- [ ] 프리즈 사용하기 기능을 구현한다.
