### ISSUE TITLE
[Feature] 공부시간 조회, 저장 구현

### ISSUE THREAD

**Issue by yooookm** [su-yeong-ice-pork/backend#33]
## 🚀 Description 
타이머 공부시간 조회, 저장 기능 구현
## ✅ TODO
- [ ] Grass 엔티티 작성
- [ ] 공부시간 조회 구현
- [ ] 공부시간 저장 구현
    - [ ] 현재 공부 시간 저장 시 전체 공부 시간도 함께 update 해야함

## 💻 etc.
- 공부 시간 필드 데이터타입을 Duration으로 설정
- request/response는 hh:mm:ss 형식의 string으로 받고 이를 service단에서 변환
