### ISSUE TITLE
[Feature] 스트릭 관련 조회 기능 구현

### ISSUE THREAD

**Issue by yooookm** [su-yeong-ice-pork/backend#39]
## 🚀 Description 
최장 스트릭, 현재 스트릭, 잔디 등 스트릭 관련 조회 기능 구현
## ✅ TODO
- [ ] 사용자 스트릭 조회
- [ ] 연간 잔디 조회
- [ ] 월간 잔디 조회

## 💻 etc.
자동 로그인 로직 변경 (기기 식별자->리프레시 토큰으로 자동 로그인)
