### ISSUE TITLE
[Feature] 회원가입 기능

### ISSUE THREAD

**Issue by MinseokGo** [su-yeong-ice-pork/backend#4]
## 🚀 Description 
회원가입 기능을 구현한다.

## ✅ TODO
- [ ] 아이디 중복 및 형식을 체크한다.
- [ ] 이름 중복 체크한다.
- [ ] 학교 이메일 중복 및 형식을 체크한다.
- [ ] 인증코드 유효성을 판별한다.
