### ISSUE TITLE
[Feature] 설정 파일의 비밀값 GitHub Secret에 등록

### ISSUE THREAD

**Issue by MinseokGo** [su-yeong-ice-pork/backend#43]
## 🚀 Description 
설정 파일의 비밀값들을 GitHub Secret에 등록한다.

## ✅ TODO
- [x] 설정값을 GitHub Secret에 등록한다.
- [x] CI/CD yaml 파일에 주입한다.
- [x] 깃허브 리포지토리를 public으로 전환한다.
