### ISSUE TITLE
[Feature] 베타 기간 회원가입 시 주어지는 뱃지 획득 기능

### ISSUE THREAD

**Issue by MinseokGo** [su-yeong-ice-pork/backend#48]
## 🚀 Description 
베타 기간 회원가입 시 주어지는 뱃지 획득 기능을 작성한다.

## ✅ TODO
- [x] '얼리어답터' 뱃지 Enum 필드를 추가한다.
- [x] MemberService의 saveMember 메서드에서 saveBetaMemberBadge 서비스로 책임을 위임해 뱃지를 저장한다.
- [x] 기존 멤버들에게는 SQL을 통해 하드 뱃지 insert를 한다.
- [ ] 베타 기간 이후 해당 로직은 삭제한다.
