### ISSUE TITLE
[REFACTOR] S3 이미지 저장 및 삭제 기능

### ISSUE THREAD

**Issue by MinseokGo** [su-yeong-ice-pork/backend#50]
## 🛠️ Description 
S3 이미지 저장 및 삭제 기능을 수정 작성한다.

## ✅ TODO
- [x] 프로필 사진 업로드 시 기존의 멤버의 프로필 사진을 삭제한다.
- [x] 새로운 프로필 사진을 업로드한다.
- [x] 프로필 배너 업로드 시 기존의 멤버의 프로필 배너를 삭제한다.
- [x] 새로운 프로필 베너를 업로드한다.
- [x] 저장 로직에서 File 대신 InputStream 을 사용한다. (아래 참고)

## 💻 etc.
![image](https://github.com/user-attachments/assets/1ca045e5-6e43-4603-b919-a293323dbd2f)
