### ISSUE TITLE
[REFACTOR] 멤버 가입 유효성 검사 기능

### ISSUE THREAD

**Issue by MinseokGo** [su-yeong-ice-pork/backend#94]
## 🛠️ Description 
멤버 가입 유효성 검사 기능을 검사한다.

## ✅ TODO
- [x] 멤버를 검사(같은 멤버인지)하는 로직을 MemberCheck 도메인에 위임한다.
- [x] 메서드 네이밍을 명확하게 한다.
- [x] 응답 구조를 와일드 카드에서 String으로 변경한다.
